### ISSUE TITLE
Can't be used in next.js without workaround

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/indexedfasta-js#52]
The isNode check ends up being true, but require('fs') fails (afaik)

Possible fix listed here, but it might be interesting to use without workaround https://github.com/GMOD/jbrowse-components/issues/1786

Workaround listed here

**Comment by rbuels** [comment]
I kind of think we should just remove the local file support in favor of just accepting filehandles, and then do a major version bump

**Comment by cmdcolin** [comment]
that is a maybe an option, but really generic-filehandle needs to be updated with a solution for this same issue too and i feel like we should figure that out before taking action here....there are also usability niceities to accepting path like you can add +'.fai' automatically
