### ISSUE TITLE
Error with example from README

### ISSUE THREAD

**Issue by nathanweeks** [GMOD/indexedfasta-js#70]
The last example in the README (substituting real .fa/.fai files):

https://github.com/GMOD/indexedfasta-js/blob/a1213b1e94e89553980b483422f5d0b5d0573538/README.md?plain=1#L64-L73

Results in the error

```
% cat example.mjs
import { IndexedFasta, BgzipIndexedFasta } from '@gmod/indexedfasta'
import { RemoteFile } from 'generic-filehandle'

const t = new IndexedFasta({
  filehandle: new RemoteFile('https://raw.githubusercontent.com/samtools/htslib/develop/test/faidx/faidx.fa', { fetch }),
  faiFilehandle: new RemoteFile('https://raw.githubusercontent.com/samtools/htslib/develop/test/faidx/faidx.fa.expected.fai', { fetch }),
})
% node example.mjs
/.../node_modules/@gmod/indexedfasta/dist/indexedFasta.js:97
            throw new Error('Need to pass filehandle for fasta or path to localfile');
                  ^

Error: Need to pass filehandle for fasta or path to localfile
    at new IndexedFasta (/.../node_modules/@gmod/indexedfasta/dist/indexedFasta.js:97:19)
    at file:///.../example.mjs:4:11
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25)

Node.js v18.15.0
```

Substituting the parameters "filehandle" and "faiFilehandle" with "fasta" and "fai", respectively, appears to resolve the issue. Is the documentation out of date, or is something else amiss?

**Comment by cmdcolin** [comment]
that is a real bug in the docs, thanks for pointing it out! actually fixed other cases of that issue recently but didn't apply to entire readme https://github.com/GMOD/indexedfasta-js/commit/c0286258c5259392e0b5022ff92f24ddd1809719

**Comment by cmdcolin** [comment]
just auto closed issue with the commit message but lemme know if anything else comes up
